# 각 외부 CSV에서 조인 후 유지하고 싶은 컬럼명 목록
# 키: 파일명, 값: 컬럼명 리스트

"서울열린데이터광장_642건.csv":
  - 상태
  - 진행단계
  - 사업번호
  - 운영구분
  - 토지등 소유자 수
  - 정비구역면적(㎡)
  - 건축연면적(㎡)
  - 용도지역
  - 용도지구,
  - 택지면적(㎡)
  - 도로면적(㎡)
  - 공원면적(㎡)
  - 녹지면적(㎡)
  - 공공공지면적(㎡)
  - 학교면적(㎡)
  - 기타면적(㎡)
  - 주용도
  - 건폐율
  - 용적률
  - 높이(m)
  - 지상층수
  - 지하층수
  - 분양세대총수
  - 60㎡이하
  - 60㎡초과~85㎡이하
  - 85㎡초과
  - 임대세대총수
  - (임대)40㎡이하
  - (임대)40㎡초과~50㎡이하
  - (임대)50㎡초과

"정비몽땅_447건.csv":
  - 사업세부분류
  - 용도지역(변경)
  
