# 표준 키 매핑 설정
# 각 파일별로 어떤 컬럼이 표준키에 해당하는지 지정합니다.

standard_keys:
  # 우선순위가 높은 식별자 및 조인 키
  - 사업번호
  - 구역명
  - 사업명
  - 자치구
  - 법정동

file_key_map:
  # 파일명은 실제 파일명과 정확히 일치해야 합니다.
  "(25년 3월기준) 서울시 정비사업 추진현황.csv":
    구역명: 구역명
    자치구: 자치구

  "(250905)서울시 재개발 재건축 정비사업 현황.csv":
    사업번호: 사업번호
    구역명: 정비구역명칭
    자치구: 자치구
    법정동: 법정동

  "서울열린데이터광장_642건.csv":
    사업번호: 사업번호
    구역명: 정비구역명칭
    자치구: 자치구
    법정동: 법정동

  "정비몽땅_447건.csv":
    사업명: 사업명
    자치구: 자치구
